---
name: Compatability

on:
    schedule:
        # Every Monday at 00:00:00 UTC.
        # @see https://crontab.cronhub.io/
        -   cron: "0 0 * * 1"

    workflow_dispatch:

jobs:
    compatability:
        name: Compatability
        runs-on: ubuntu-latest
        steps:
            -   name: Install rsync
                uses: GuillaumeFalourd/setup-rsync@v1.2 # https://github.com/marketplace/actions/setup-rsync

            -   name: Set up PHP
                uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
                with:
                    php-version: '8.3'
                    coverage: none

            -   name: Checkout code
                uses: actions/checkout@v4 # https://github.com/marketplace/actions/checkout

            -   name: Install dependencies
                uses: ramsey/composer-install@v3 # https://github.com/marketplace/actions/install-composer-dependencies

            -   name: Run compatability tests
                run: composer compatability
